### ISSUE TITLE
Some question after running the model

### ISSUE THREAD

**Issue by zysforever** [shawnkx/Decom#2]
After I run the command `python main.py model DistMultDecompress dataset FB15k-237 lr  0.001 hidden_drop 0.2 epochs 30 process False`, an error happens: "AttributeError: 'StreamBatcher' object has no attribute 'loaders'" . Did I do something wrong? Could you help me to solve this? Looking forward to your reply!
![ER7Z76}{1UN J6LX6INLUKF](https://user-images.githubusercontent.com/20456940/70512830-5f260800-1b6b-11ea-938f-c655661857cb.png)

**Comment by shawnkx** [comment]
there is an exception in your error message: Path /home/zys/.data/. .. have your forgotten to preprocess your dataset? 
Maybe your need to remove process False, jus try 

``
python main.py model DistMultDecompress dataset FB15k-237 lr 0.001 hidden_drop 0.2 epochs 30
``

**Comment by zysforever** [comment]
> there is an exception in your error message: Path /home/zys/.data/. .. have your forgotten to preprocess your dataset?
> Maybe your need to remove process False, jus try
> 
> `python main.py model DistMultDecompress dataset FB15k-237 lr 0.001 hidden_drop 0.2 epochs 30`

I have preprocessed the dadasets by `sh preprocess.sh` and removed process False, but it still didn't work and showed the same error: "AttributeError: 'StreamBatcher' object has no attribute 'loaders'". By the way, after I run `sh preprocess.sh`, there are 7 files in FB15k-237(like the photo). Is there something wrong?
![9AK0N60_92A2J{`C) D89$X](https://user-images.githubusercontent.com/20456940/70693689-e8b71080-1cf8-11ea-837c-065aa4d03b89.png)

**Comment by shawnkx** [comment]
My bad. Could you add process True to your command?
Like
```
python main.py model DistMultDecompress dataset FB15k-237 lr 0.001 hidden_drop 0.2 epochs 30 process True
```
Maybe you do not process your data before training. If it doesn't work either, please tell me and I will check our code.

**Comment by zysforever** [comment]
> My bad. Could you add process True to your command?
> Like
> 
> ```
> python main.py model DistMultDecompress dataset FB15k-237 lr 0.001 hidden_drop 0.2 epochs 30 process True
> ```
> 
> Maybe you do not process your data before training. If it doesn't work either, please tell me and I will check our code.

It works! After I added "process True", it showed the result in the photo. But the results of each index are about 1% less than those in your paper. 
![62XVF {GKEKYWXUCM9$9UA4](https://user-images.githubusercontent.com/20456940/70786704-32226100-1dc8-11ea-8423-dcbe7c8c747c.png)

**Comment by shawnkx** [comment]
the screenshot is for dev evaluation right? And you need more epochs to match the number in the paper. epoch 30 is just a trial number.

**Comment by zysforever** [comment]
> the screenshot is for dev evaluation right? And you need more epochs to match the number in the paper. epoch 30 is just a trial number.

I will try it. Thank you very much!
